<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRenavalsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     *
     */
    public function up()
    {
        Schema::create('renavals', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id');
            $table->string('centro_salud')->nullable();
            $table->string('documento_identidad')->nullable();
            $table->string('modalidad_ingreso',20)->nullable();
            $table->string('departamento',150)->nullable();
            $table->string('provincia',150)->nullable();
            $table->string('ciudad',150)->nullable();
            $table->integer('edad')->nullable();
            $table->string('sexo',20)->nullable();
            $table->string('gestante',2)->nullable();
            $table->string('estado_civil',20)->nullable();
            $table->string('grado_instruccion',50)->nullable();
            $table->string('compli_enfermedad',150)->nullable();
            $table->string('pas_diagnostico',10)->nullable();
            $table->string('pad_diagnostico',10)->nullable();
            $table->string('peso',10)->nullable();
            $table->integer('talla')->nullable();
            $table->integer('circunferencia_abdominal')->nullable();
            $table->text('antecedentes')->nullable();
            $table->string('metodo_diagnostico_valvulopatia',200)->nullable();
            $table->date('fecha_diagnostico_valvulopatia')->nullable();
            $table->integer('fevi_al_diagnostico')->nullable();
            $table->string('diagnostico_estenosis')->nullable();
            $table->string('diagnostico_insuficiencia')->nullable();
            $table->string('enfermedad_valvular_multiple',2)->nullable();
            $table->text('etiologias')->nullable();
            $table->string('etiologias_otro',150)->nullable();
            $table->string('cha2ds2vasc')->nullable();
            $table->text('diagnostico')->nullable();
            $table->string('clasif_nyha')->nullable();
            $table->string('enf_coronaria',2)->nullable();
            $table->string('ea_morfologia_valvula_estenosis_aortica',50)->nullable();
            $table->string('ea_morfologia_valvula_estenosis_aortica_otro',100)->nullable();
            $table->string('ea_velocidad_maxima',10)->nullable();
            $table->string('ea_area_valvular',10)->nullable();
            $table->string('ea_gradiente_media',10)->nullable();
            $table->string('ea_calculo_area_valvular',50)->nullable();
            $table->string('ea_severidad_valvulopatia',20)->nullable();
            $table->string('ea_etiologia',200)->nullable();
            $table->string('ea_volumen_sistolico_eyeccion',10)->nullable();
            $table->string('ia_jet',20)->nullable();
            $table->string('ia_vena_contracta',10)->nullable();
            $table->string('ia_ore',10)->nullable();
            $table->string('ia_vol_regurgitante_orificio',10)->nullable();
            $table->string('ia_etiologia')->nullable();
            $table->string('ia_severidad',20)->nullable();
            $table->string('em_score_wilkins')->nullable();
            $table->string('em_gradiente_media',10)->nullable();
            $table->string('em_tiempo_hemipresion',10)->nullable();
            $table->string('em_area_val_mitral',10)->nullable();
            $table->string('em_etiologia')->nullable();
            $table->string('em_severidad',20)->nullable();
            $table->string('im_jet',20)->nullable();
            $table->string('im_vena_contracta',10)->nullable();
            $table->string('im_ore',10)->nullable();
            $table->string('im_volumen_regurgitante',10)->nullable();
            $table->string('im_etiologia')->nullable();
            $table->string('im_severidad',20)->nullable();
            $table->string('im_carpentier')->nullable();
            $table->string('im_anillo',10)->nullable();
            $table->string('im_metodo_eval_anillo')->nullable();
            $table->string('et_velocidad_maxima',10)->nullable();
            $table->string('et_gradiente_media',10)->nullable();
            $table->string('et_area_valvular',10)->nullable();
            $table->string('et_etiologia')->nullable();
            $table->string('et_severidad',20)->nullable();
            $table->integer('it_numero_velos')->nullable();
            $table->string('it_jet',20)->nullable();
            $table->string('it_vena_contracta',10)->nullable();
            $table->string('it_ore',10)->nullable();
            $table->string('it_velocidad_maxima',10)->nullable();
            $table->string('it_gradiente_maxima',10)->nullable();
            $table->string('it_volumen_regurgitante',10)->nullable();
            $table->string('it_severidad',20)->nullable();
            $table->string('it_psap_estimada',10)->nullable();
            $table->string('it_anillo',10)->nullable();
            $table->string('it_metodo_eval_anillo')->nullable();
            $table->string('ep_velocidad_maxima',10)->nullable();
            $table->string('ep_gradiente_media',10)->nullable();
            $table->string('ep_area_valvular',10)->nullable();
            $table->string('ep_etiologia')->nullable();
            $table->string('ep_severidad',20)->nullable();
            $table->string('ip_vena_contracta',10)->nullable();
            $table->string('ip_etiologia')->nullable();
            $table->string('ip_severidad',20)->nullable();
            $table->string('ip_anillo',10)->nullable();
            $table->string('ip_metodo_eval_anillo')->nullable();
            $table->string('volumen_auricula_izquierda',10)->nullable();
            $table->string('area_auricula_derecha',10)->nullable();
            $table->string('vi_diametro_telesistolico',10)->nullable();
            $table->string('vi_volumen_telediastolico',10)->nullable();
            $table->string('vi_volumen_telesistolico',10)->nullable();
            $table->string('vi_masa',10)->nullable();
            $table->string('vi_remodelamiento',60)->nullable();
            $table->string('vi_fraccion_eyeccion_simpson',5)->nullable();
            $table->string('vd_base',5)->nullable();
            $table->string('vd_porcion_media',5)->nullable();
            $table->string('vd_longitud',5)->nullable();
            $table->string('vd_dilatado',5)->nullable();
            $table->string('vd_tapse',5)->nullable();
            $table->integer('vd_fraccion_acortamiento')->nullable();
            $table->integer('rda_union')->nullable();
            $table->integer('rda_senos')->nullable();
            $table->integer('rda_anillo')->nullable();
            $table->integer('rda_aorta_ascendente')->nullable();
            $table->date('cci_fecha',5)->nullable();
            $table->string('lesion_cd',2)->nullable();
            $table->string('lesion_tci',2)->nullable();
            $table->string('lesion_ada',2)->nullable();
            $table->string('lesion_cx',2)->nullable();
            $table->string('lesion_diagonal',2)->nullable();
            $table->string('lesion_marginal',2)->nullable();
            $table->string('lesion_descen_posterior',2)->nullable();
            $table->date('ccd_fecha')->nullable();
            $table->integer('ccd_presartesis_pulmonar')->nullable();
            $table->integer('ccd_psap_cardercho')->nullable();
            $table->string('ccd_resis_pulmonar',50)->nullable();
            $table->integer('ccd_presart_medpulmunar')->nullable();
            $table->string('ccd_hiper_pulmonar',2)->nullable();
            $table->string('ccd_diag_hipertension',100)->nullable();
            $table->integer('ccd_diam_vi_diastole')->nullable();
            $table->integer('ccd_diam_vi_sistole')->nullable();
            $table->date('fecha_intervencion')->nullable();
            $table->string('valvulas_tratadas',150)->nullable();
            $table->string('tratamiento',30)->nullable();
            $table->string('reparacion',2)->nullable();
            $table->string('valvula_reparada',50)->nullable();
            $table->string('dispositivos',2)->nullable();
            $table->string('valvula_trat_dispositivo',100)->nullable();
            $table->string('protesis',15)->nullable();
            $table->string('valvula_tratada_protesis',100)->nullable();
            $table->string('otros_procedquirurgicos',200)->nullable();
            $table->string('interv_tipodispusado',200)->nullable();
            $table->string('medicacion_ieca',2)->nullable();
            $table->string('medicacion_ara',2)->nullable();
            $table->string('medicacion_betabloqueador',2)->nullable();
            $table->string('medicacion_digoxina',2)->nullable();
            $table->string('medicacion_estatinas',2)->nullable();
            $table->string('medicacion_diureticos',2)->nullable();
            $table->string('medicacion_calcio_antagonista',2)->nullable();
            $table->string('medicacion_dabigatran',2)->nullable();
            $table->string('medicacion_warfarina',2)->nullable();
            $table->string('medicacion_acido_acetil_salicilico',2)->nullable();
            $table->string('medicacion_otro',150)->nullable();
            $table->string('inmediatas',150)->nullable();
            $table->string('tardias',150)->nullable();
            $table->string('muerte_general',2)->nullable();
            $table->string('muerte_cardiovascular',2)->nullable();
            $table->date('fechademuerte')->nullable();
            $table->string('hospitalizacion',2)->nullable();
            $table->integer('tiempo_hospitalizacion')->nullable();
            $table->date('fecha_hospitalizacion')->nullable();
            $table->string('status');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('renavals');
    }
}
