<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Repecca extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'tipo_seguro',
        'tipo_seguro_otro',
        'fecha_ultima_atencion',
        'numero_historia_clinica',
        'sexo',
        'edad',
        'estado_civil',
        'grado_instruccion',
        'actividad_laboral',
        'numero_gestas',
        'partos_a_termino',
        'partos_pretermino',
        'abortos',
        'numero_hijos_vivos',
        'diagnostico_especifico',
        'transicion_cardiologia',
        'sindrome_genetico_asociado',
        'sindrome_genetico_asociado_otro',
        'severidad',
        'clasificacion_anatomica_funcional',
        'clase_funcional',
        'dependencia_funcional',
        'hospitalizaciones',
        'cianosis',
        'saturacion_oxigeno',
        'peso',
        'talla',
        'manejo_recibido',
        'manejo_recibido_otro',
        'protesis_valvulares',
        'ubicacion_protesis_valvulares_aortica',
        'ubicacion_protesis_valvulares_mitral',
        'ubicacion_protesis_valvulares_pulmonar',
        'ubicacion_protesis_valvulares_tricuspide',
        'procedimiento_electrofisiologico',
        'marcapasos',
        'aortoplastia',
        'stent_fistulas',
        'cirugia_cardiaca',
        'ventriculo_sistemico',
        'fraccion_eyeccion',
        'funcion_sistolica',
        'tratamiento_medico',
        'tratamiento_medico_otro',
        'arritmias',
        'arritmias_otro',
        'comorbilidades',
        'comorbilidades_otro',
        'enfermedad_renal',
        'complicaciones',
        'uso_dispositivos',
        'uso_dispositivos_otro',
        'creatinina_serica',
        'acido_urico_serico',
        'glucosa_serica',
        'colesterol_total',
        'colesterol_ldl',
        'trigliceridos',
        'hemoglobina',
        'hematocrito',
        'plaquetas',
        'ferritina',
        'hierro_serico',
        'saturacion_transferrina',
        'tsh',
        't4_libre',
    ];
}
